export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const ADD_TODO_ITEM = 'ADD_TODO_ITEM'
export const DONE_TODO_ITEM = 'DONE_TODO_ITEM'
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM'
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM'
export const GET_TODO_ITEMS = 'GET_TODO_ITEMS'
